// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OpeningIntroVideo","status":true,"description":"Play opening intro video before title scene.","parameters":{"MovieFile":"infinium_opening.mp4","AllowSkip":"true"}},
{"name":"TitlePosterSlideshow","status":true,"description":"Rotate title posters every 3 seconds.","parameters":{"Images":"[\"InfiniumPoster01\",\"InfiniumPoster02\",\"InfiniumPoster03\"]","ChineseImages":"[\"InfiniumPoster01\",\"InfiniumPoster02\",\"InfiniumPoster03\"]","EnglishImages":"[\"InfiniumPoster01\",\"InfiniumPoster02\",\"InfiniumPoster03\"]","Interval":"180","DefaultLanguage":"zh"}},
{"name":"InfiniumDialogueI18n","status":true,"description":"INFINIUM dialogue CN/EN switch (follows title language selection).","parameters":{}},
{"name":"InfiniumMinimalMenu","status":true,"description":"Keep map menu minimal: Options / Save / End Game only.","parameters":{}}
];
